application:
  version: 1.0
  exclude-urls:
    - /login
    - /system/**
server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dbip}:3306/oskdb?useUnicode=true&useSSL=true&autoReconnect=true
    username: oskdb
    password: ${dbpasswd}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sa-token:
    token-name: Authentication