server:
  port: 8080
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/pd_hym?useUnicode=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
