application:
  version: 1.0
  excludeUrls:
    - /login
    - /system/**
server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dbip}:3306/oskdb?useUnicode=true&useSSL=true&autoReconnect=true
    username: oskdb
    password: ${dbpasswd}
  jpa:
    show-sql: true
