application:
  version: 1.0
  exclude-urls:
    - /version
    - /device/keepalive
    - /device/sampled
    - /login
    - /join
server:
  port: 8089


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dbip}:3309/oskdb?useUnicode=true&useSSL=true&autoReconnect=true
    username: root
    password: ${dbpasswd}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sa-token:
    token-name: Authentication
    is-read-cookie: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
